excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  # - Source/ExcludedFolder
  # - Source/ExcludedFile.swift
disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
opt_in_rules: # some rules are only opt-in
  - attributes
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - for_where
  - missing_docs
  - nimble_operator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - redundant_nil_coalescing
  - sorted_imports
  - switch_case_on_newline

# configurable rules
cyclomatic_complexity:
  warning: 4
  error: 6
empty_count:
  severity: warning
file_length:
  warning: 300
  error: 1000
force_cast:
  severity: warning
force_try:
  severity: warning
function_body_length:
  warning: 30
large_tuple:
  warning: 3
  error: 4
line_length: 150
