excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  # - Source/ExcludedFolder
  # - Source/ExcludedFile.swift
disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
opt_in_rules: # some rules are only opt-in
  - attributes
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - for_where
  - missing_docs
  - nimble_operator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - redundant_nil_coalescing
  - sorted_imports
  - switch_case_on_newline

# configurable rules
cyclomatic_complexity:
  warning: 4
  error: 6

empty_count:
  severity: warning

file_length:
  warning: 300
  error: 1000

force_cast:
  severity: warning

force_try:
  severity: warning

function_body_length:
  warning: 30
  error: 50

large_tuple:
  warning: 3
  error: 4

line_length: 150 # only warning

type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: # excluded via string
    - T
    - t

variable_name:
  min_length: 3 # only min_length and only warning
  excluded: # excluded via string array
    - id
    - vc
    - to
    - a
    - b
    - t
    - x
    - y
    - z
    - p
    - xy
    - dx
    - dy
    - gr
